<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace GPBMetadata;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê	
account.protoJason.Chain33.Kernel.Protobuf"J
Account
currency (
balance (
frozen (
addr (	"ù
ReceiptExecAccountTransfer
execAddr (	4
prev (2&.Jason.Chain33.Kernel.Protobuf.Account7
current (2&.Jason.Chain33.Kernel.Protobuf.Account"á
ReceiptAccountTransfer4
prev (2&.Jason.Chain33.Kernel.Protobuf.Account7
current (2&.Jason.Chain33.Kernel.Protobuf.Account"É
ReceiptAccountMint4
prev (2&.Jason.Chain33.Kernel.Protobuf.Account7
current (2&.Jason.Chain33.Kernel.Protobuf.Account"É
ReceiptAccountBurn4
prev (2&.Jason.Chain33.Kernel.Protobuf.Account7
current (2&.Jason.Chain33.Kernel.Protobuf.Account"l

ReqBalance
	addresses (	
execer (	
	stateHash (	

asset_exec (	
asset_symbol (	"?
Accounts3
acc (2&.Jason.Chain33.Kernel.Protobuf.Account"V
ExecAccount
execer (	7
account (2&.Jason.Chain33.Kernel.Protobuf.Account"_
AllExecBalance
addr (	?
ExecAccount (2*.Jason.Chain33.Kernel.Protobuf.ExecAccount"n
ReqAllExecBalance
addr (	
execer (	
	stateHash (	

asset_exec (	
asset_symbol (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

