<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace GPBMetadata;

class Blockchain
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Transaction::initOnce();
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            '
«&
blockchain.protoJason.Chain33.Kernel.Protobufcommon.proto"ã
Header
version (

parentHash (
txHash (
	stateHash (
height (
	blockTime (
txCount	 (
hash
 (

difficulty (;
	signature (2(.Jason.Chain33.Kernel.Protobuf.Signature"¢
Block
version (

parentHash (
txHash (
	stateHash (
height (
	blockTime (

difficulty (
mainHash (

mainHeight (;
	signature (2(.Jason.Chain33.Kernel.Protobuf.Signature7
txs (2*.Jason.Chain33.Kernel.Protobuf.Transaction"=
Blocks3
items (2$.Jason.Chain33.Kernel.Protobuf.Block"Ž
BlockSeq
num (9
seq (2,.Jason.Chain33.Kernel.Protobuf.BlockSequence:
detail (2*.Jason.Chain33.Kernel.Protobuf.BlockDetail"B
	BlockSeqs5
seqs (2\'.Jason.Chain33.Kernel.Protobuf.BlockSeq"L
BlockPid
pid (	3
block (2$.Jason.Chain33.Kernel.Protobuf.Block"I
BlockDetails9
items (2*.Jason.Chain33.Kernel.Protobuf.BlockDetail"?
Headers4
items (2%.Jason.Chain33.Kernel.Protobuf.Header"R

HeadersPid
pid (	7
headers (2&.Jason.Chain33.Kernel.Protobuf.Headers"g
BlockOverview3
head (2%.Jason.Chain33.Kernel.Protobuf.Header
txCount (
txHashes ("Í
BlockDetail3
block (2$.Jason.Chain33.Kernel.Protobuf.Block<
receipts (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData3
KV (2\'.Jason.Chain33.Kernel.Protobuf.KeyValue
prevStatusHash ("D
Receipts8
receipts (2&.Jason.Chain33.Kernel.Protobuf.Receipt""
ReceiptCheckTxList
errs (	"O
ChainStatus
currentHeight (
mempoolSize (
msgQueueSize ("F
	ReqBlocks
start (
end (
isDetail (
pid (	"
MempoolSize
size (""
ReplyBlockHeight
height ("Æ
	BlockBody7
txs (2*.Jason.Chain33.Kernel.Protobuf.Transaction<
receipts (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData
mainHash (

mainHeight (
hash (
height ("j
BlockReceipt<
receipts (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData
hash (
height (" 

IsCaughtUp

Iscaughtup ("(
IsNtpClockSync
isntpclocksync ("b
ChainExecutor
driver (	
funcName (	
	stateHash (
param (
extra ("+
BlockSequence
Hash (
Type ("M
BlockSequences;
items (2,.Jason.Chain33.Kernel.Protobuf.BlockSequence"y
ParaChainBlockDetail?
blockdetail (2*.Jason.Chain33.Kernel.Protobuf.BlockDetail
sequence (
isSync ("K
ParaTxDetails:
items (2+.Jason.Chain33.Kernel.Protobuf.ParaTxDetail"Á
ParaTxDetail
type (5
header (2%.Jason.Chain33.Kernel.Protobuf.Header:
	txDetails (2\'.Jason.Chain33.Kernel.Protobuf.TxDetail
	childHash (
index (
proofs ("ž
TxDetail
index (6
tx (2*.Jason.Chain33.Kernel.Protobuf.Transaction;
receipt (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData
proofs ("L
ReqParaTxByTitle
start (
end (
title (	
isSeq ("Q

FileHeader
startHeight (
driver (	
title (	
testNet ("(
EndBlock
height (
hash ("Š
	HeaderSeq
num (9
seq (2,.Jason.Chain33.Kernel.Protobuf.BlockSequence5
header (2%.Jason.Chain33.Kernel.Protobuf.Header"D

HeaderSeqs6
seqs (2(.Jason.Chain33.Kernel.Protobuf.HeaderSeq"‰

HeightPara
height (
title (	
hash (
	childHash (

startIndex (
childHashIndex (
txCount ("G
HeightParas8
items (2).Jason.Chain33.Kernel.Protobuf.HeightPara"S

ChildChain
title (	

startIndex (
	childHash (
txCount ("S
ReqHeightByTitle
height (
title (	
count (
	direction ("\\
ReplyHeightByTitle
title (	7
items (2(.Jason.Chain33.Kernel.Protobuf.BlockInfo")
	BlockInfo
height (
hash ("1
ReqParaTxByHeight
items (
title (	"P
CmpBlock3
block (2$.Jason.Chain33.Kernel.Protobuf.Block
cmpHash ("E

BlockBodys7
items (2(.Jason.Chain33.Kernel.Protobuf.BlockBody"G
ChunkRecords7
infos (2(.Jason.Chain33.Kernel.Protobuf.ChunkInfo"=
ChunkInfoMsg
	chunkHash (
start (
end ("L
	ChunkInfo
chunkNum (
	chunkHash (
start (
end ("L
ReqChunkRecords
start (
end (
isDetail (
pid (	"Ž
PushSubscribeReq
name (	
URL (	
encode (	
lastSequence (

lastHeight (
lastBlockHash (	
type (O
contract (2=.Jason.Chain33.Kernel.Protobuf.PushSubscribeReq.ContractEntry/
ContractEntry
key (	
value (:8"_
PushWithStatus=
push (2/.Jason.Chain33.Kernel.Protobuf.PushSubscribeReq
status ("Q
PushSubscribes?
pushes (2/.Jason.Chain33.Kernel.Protobuf.PushSubscribeReq"/
ReplySubscribePush
isOk (
msg (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

