<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
²
common.protoJason.Chain33.Kernel.Protobuf""
Reply
isOk (
msg ("
	ReqString
data (	"
ReplyString
data (	"
ReplyStrings
datas (	"
ReqInt
height ("
Int64
data ("(
ReqHash
hash (
upgrade ("
	ReplyHash
hash ("
ReqNil"
	ReqHashes
hashes ("
ReplyHashes
hashes ("&
KeyValue
key (
value ("
TxHash
hash (	">

TimeStatus
ntpTime (	
	localTime (	
diff ("
ReqKey
key ("O
ReqRandHash
execName (	
height (
blockNum (
hash ("\\
VersionInfo
title (	
app (	
chain33 (	
localDb (	
chainID (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

