<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic.proto

namespace GPBMetadata;

class Statistic
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
†
statistic.protoJason.Chain33.Kernel.Protobuf"(
TotalFee
fee (
txCount ("f
ReqGetTotalCoins
symbol (	
	stateHash (
startKey (
count (
execer (	"Q
ReplyGetTotalCoins
count (
num (
amount (
nextKey ("W
IterateRangeByStateHash
	stateHash (
start (
end (
count ("
TotalAmount
total ("†
ReqGetExecBalance
symbol (	
	stateHash (
addr (
execAddr (
execer (	
count (
nextKey ("C
ExecBalanceItem
execAddr (
frozen (
active ("¡
ReplyGetExecBalance
amount (
amountFrozen (
amountActive (
nextKey (=
items (2..Jason.Chain33.Kernel.Protobuf.ExecBalanceItembproto3'
        , true);

        static::$is_initialized = true;
    }
}

