<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace GPBMetadata;

class Transaction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            '
÷
transaction.protoJason.Chain33.Kernel.Protobuf"6
AssetsGenesis
amount (
returnAddress (	"e
AssetsTransferToExec
	cointoken (	
amount (
note (
execName (	

to (	"_
AssetsWithdraw
	cointoken (	
amount (
note (
execName (	

to (	"M
AssetsTransfer
	cointoken (	
amount (
note (

to (	"5
Asset
exec (	
symbol (	
amount ("ù
CreateTx

to (	
amount (
fee (
note (

isWithdraw (
isToken (
tokenSymbol (	
execName (	
execer	 (	"R
ReWriteRawTx

tx (	

to (	
expire (	
fee (
index ("%
CreateTransactionGroup
txs (	"
UnsignTx
data ("P
NoBalanceTxs
txHexs (	
payAddr (	
privkey (	
expire (	"N
NoBalanceTx
txHex (	
payAddr (	
privkey (	
expire (	"Ê
Transaction
execer (
payload (;
	signature (2(.Jason.Chain33.Kernel.Protobuf.Signature
fee (
expire (
nonce (

to (	

groupCount (
header	 (
next
 (
chainID ("G
Transactions7
txs (2*.Jason.Chain33.Kernel.Protobuf.Transaction"P
RingSignature?
items (20.Jason.Chain33.Kernel.Protobuf.RingSignatureItem"6
RingSignatureItem
pubkey (
	signature (":
	Signature

ty (
pubkey (
	signature ("A
AddrOverview
reciver (
balance (
txCount ("f
ReqAddr
addr (	
flag (
count (
	direction (
height (
index ("
HexTx

tx (	"p
ReplyTxInfo
hash (
height (
index (4
assets (2$.Jason.Chain33.Kernel.Protobuf.Asset"
	ReqTxList
count ("F
ReplyTxList7
txs (2*.Jason.Chain33.Kernel.Protobuf.Transaction"
ReqGetMempool
isAll ("/
ReqProperFee
txCount (
txSize ("#
ReplyProperFee
	properFee (";

TxHashList
hashes (
count (
expire ("K
ReplyTxInfos;
txInfos (2*.Jason.Chain33.Kernel.Protobuf.ReplyTxInfo"%

ReceiptLog

ty (
log ("É
Receipt

ty (3
KV (2\'.Jason.Chain33.Kernel.Protobuf.KeyValue7
logs (2).Jason.Chain33.Kernel.Protobuf.ReceiptLog"R
ReceiptData

ty (7
logs (2).Jason.Chain33.Kernel.Protobuf.ReceiptLog"…
TxResult
height (
index (6
tx (2*.Jason.Chain33.Kernel.Protobuf.Transaction?
receiptdate (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData
	blocktime (

actionName (	"Ç
TransactionDetail6
tx (2*.Jason.Chain33.Kernel.Protobuf.Transaction;
receipt (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData
proofs (
height (
index (
	blocktime (
amount (
fromaddr (	

actionName	 (	4
assets
 (2$.Jason.Chain33.Kernel.Protobuf.Asset8
txProofs (2&.Jason.Chain33.Kernel.Protobuf.TxProof
fullHash ("S
TransactionDetails=
txs (20.Jason.Chain33.Kernel.Protobuf.TransactionDetail"
ReqAddrs
addrs (	"(
ReqDecodeRawTransaction
txHex (	"+
	UserWrite
topic (	
content (	"@
UpgradeMeta
starting (
version (	
height ("4
ReqTxHashList
hashes (	
isShortHash (":
TxProof
proofs (
index (
rootHash ("$
ReqCheckTxsExist
txHashes ("<
ReplyCheckTxsExist

existFlags (

existCount (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

