<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace GPBMetadata;

class Wallet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Transaction::initOnce();
        \GPBMetadata\Account::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ï
wallet.protoJason.Chain33.Kernel.Protobufaccount.proto"é
WalletTxDetail6
tx (2*.Jason.Chain33.Kernel.Protobuf.Transaction;
receipt (2*.Jason.Chain33.Kernel.Protobuf.ReceiptData
height (
index (
	blocktime (
amount (
fromaddr (	
txhash (

actionName	 (	
payload
 ("S
WalletTxDetails@
	txDetails (2-.Jason.Chain33.Kernel.Protobuf.WalletTxDetail"U
WalletAccountStore
privkey (	
label (	
addr (	
	timeStamp (	"/
WalletPwHash
pwHash (
randstr (	"c
WalletStatus
isWalletLock (
isAutoMining (
	isHasSeed (
isTicketLock ("O
WalletAccounts=
wallets (2,.Jason.Chain33.Kernel.Protobuf.WalletAccount"S
WalletAccount3
acc (2&.Jason.Chain33.Kernel.Protobuf.Account
label (	"G
WalletUnLock
passwd (	
timeout (
walletOrTicket ("
GenSeedLang
lang ("
GetSeedByPw
passwd (	",
SaveSeedByPw
seed (	
passwd (	"
	ReplySeed
seed (	"6
ReqWalletSetPasswd
oldPass (	
newPass (	"
ReqNewAccount
label (	"
ReqGetAccount
label (	"L
ReqWalletTransactionList
fromTx (
count (
	direction ("8
ReqWalletImportPrivkey
privkey (	
label (	"v
ReqWalletSendToAddress
from (	

to (	
amount (
note (	
isToken (
tokenSymbol (	"!
ReqWalletSetFee
amount ("0
ReqWalletSetLabel
addr (	
label (	"#
ReqWalletMergeBalance

to (	"è
ReqTokenPreCreate
creator_addr (	
name (	
symbol (	
introduction (	

owner_addr (	
total (
price ("Q
ReqTokenFinishCreate
finisher_addr (	
symbol (	

owner_addr (	"P
ReqTokenRevokeCreate
revoker_addr (	
symbol (	

owner_addr (	"K
ReqModifyConfig
key (	

op (	
value (	
modifier (	"ä
ReqSignRawTx
addr (	
privkey (	
txHex (	
expire (	
index (
token (	
fee (
	newToAddr
 (	"
ReplySignRawTx
txHex (	"E
ReportErrEvent

frommodule (	
tomodule (	
error (	"
Int32
data ("(
ReqAccountList
withoutBalance ("3
ReqPrivkeysFile
fileName (	
passwd (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

