<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.AllExecBalance</code>
 */
class AllExecBalance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string addr = 1;</code>
     */
    protected $addr = '';
    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ExecAccount ExecAccount = 2;</code>
     */
    private $ExecAccount;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addr
     *     @type \Jason\Chain33\Kernel\Protobuf\ExecAccount[]|\Google\Protobuf\Internal\RepeatedField $ExecAccount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string addr = 1;</code>
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Generated from protobuf field <code>string addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ExecAccount ExecAccount = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExecAccount()
    {
        return $this->ExecAccount;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ExecAccount ExecAccount = 2;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\ExecAccount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExecAccount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jason\Chain33\Kernel\Protobuf\ExecAccount::class);
        $this->ExecAccount = $arr;

        return $this;
    }

}

