<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.AssetsTransfer</code>
 */
class AssetsTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cointoken = 1;</code>
     */
    protected $cointoken = '';
    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>bytes note = 3;</code>
     */
    protected $note = '';
    /**
     * Generated from protobuf field <code>string to = 4;</code>
     */
    protected $to = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cointoken
     *     @type int|string $amount
     *     @type string $note
     *     @type string $to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cointoken = 1;</code>
     * @return string
     */
    public function getCointoken()
    {
        return $this->cointoken;
    }

    /**
     * Generated from protobuf field <code>string cointoken = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCointoken($var)
    {
        GPBUtil::checkString($var, True);
        $this->cointoken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes note = 3;</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>bytes note = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, False);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to = 4;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>string to = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;

        return $this;
    }

}

