<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * assert transfer struct
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.AssetsGenesis</code>
 */
class AssetsGenesis extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string returnAddress = 3;</code>
     */
    protected $returnAddress = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $amount
     *     @type string $returnAddress
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string returnAddress = 3;</code>
     * @return string
     */
    public function getReturnAddress()
    {
        return $this->returnAddress;
    }

    /**
     * Generated from protobuf field <code>string returnAddress = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReturnAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->returnAddress = $var;

        return $this;
    }

}

