<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *区块视图
 * 	 head : 区块头信息
 *	 txCount :区块上交易个数
 * 	 txHashes : 区块上交易的哈希列表
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.BlockOverview</code>
 */
class BlockOverview extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Header head = 1;</code>
     */
    protected $head = null;
    /**
     * Generated from protobuf field <code>int64 txCount = 2;</code>
     */
    protected $txCount = 0;
    /**
     * Generated from protobuf field <code>repeated bytes txHashes = 3;</code>
     */
    private $txHashes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Jason\Chain33\Kernel\Protobuf\Header $head
     *     @type int|string $txCount
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $txHashes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Header head = 1;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\Header|null
     */
    public function getHead()
    {
        return isset($this->head) ? $this->head : null;
    }

    public function hasHead()
    {
        return isset($this->head);
    }

    public function clearHead()
    {
        unset($this->head);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Header head = 1;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\Header $var
     * @return $this
     */
    public function setHead($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\Header::class);
        $this->head = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 2;</code>
     * @return int|string
     */
    public function getTxCount()
    {
        return $this->txCount;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->txCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes txHashes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxHashes()
    {
        return $this->txHashes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes txHashes = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxHashes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->txHashes = $arr;

        return $this;
    }

}

