<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *  通过block hash记录block的操作类型及add/del：1/2
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.BlockSequence</code>
 */
class BlockSequence extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Hash = 1;</code>
     */
    protected $Hash = '';
    /**
     * Generated from protobuf field <code>int64 Type = 2;</code>
     */
    protected $Type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Hash
     *     @type int|string $Type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->Hash;
    }

    /**
     * Generated from protobuf field <code>bytes Hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->Hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Type = 2;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int64 Type = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->Type = $var;

        return $this;
    }

}

