<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ChainExecutor</code>
 */
class ChainExecutor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string driver = 1;</code>
     */
    protected $driver = '';
    /**
     * Generated from protobuf field <code>string funcName = 2;</code>
     */
    protected $funcName = '';
    /**
     * Generated from protobuf field <code>bytes stateHash = 3;</code>
     */
    protected $stateHash = '';
    /**
     * Generated from protobuf field <code>bytes param = 4;</code>
     */
    protected $param = '';
    /**
     *扩展字段，用于额外的用途
     *
     * Generated from protobuf field <code>bytes extra = 5;</code>
     */
    protected $extra = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $driver
     *     @type string $funcName
     *     @type string $stateHash
     *     @type string $param
     *     @type string $extra
     *          扩展字段，用于额外的用途
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string driver = 1;</code>
     * @return string
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Generated from protobuf field <code>string driver = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDriver($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string funcName = 2;</code>
     * @return string
     */
    public function getFuncName()
    {
        return $this->funcName;
    }

    /**
     * Generated from protobuf field <code>string funcName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFuncName($var)
    {
        GPBUtil::checkString($var, True);
        $this->funcName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 3;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes param = 4;</code>
     * @return string
     */
    public function getParam()
    {
        return $this->param;
    }

    /**
     * Generated from protobuf field <code>bytes param = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, False);
        $this->param = $var;

        return $this;
    }

    /**
     *扩展字段，用于额外的用途
     *
     * Generated from protobuf field <code>bytes extra = 5;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     *扩展字段，用于额外的用途
     *
     * Generated from protobuf field <code>bytes extra = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, False);
        $this->extra = $var;

        return $this;
    }

}

