<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ConfigItem</code>
 */
class ConfigItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>string addr = 2;</code>
     */
    protected $addr = '';
    /**
     * Generated from protobuf field <code>int32 Ty = 11;</code>
     */
    protected $Ty = 0;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $addr
     *     @type \Jason\Chain33\Kernel\Protobuf\ArrayConfig $arr
     *     @type \Jason\Chain33\Kernel\Protobuf\StringConfig $str
     *     @type \Jason\Chain33\Kernel\Protobuf\Int32Config $int
     *     @type int $Ty
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Executor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string addr = 2;</code>
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Generated from protobuf field <code>string addr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ArrayConfig arr = 3;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\ArrayConfig|null
     */
    public function getArr()
    {
        return $this->readOneof(3);
    }

    public function hasArr()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ArrayConfig arr = 3;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\ArrayConfig $var
     * @return $this
     */
    public function setArr($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\ArrayConfig::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.StringConfig str = 4;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\StringConfig|null
     */
    public function getStr()
    {
        return $this->readOneof(4);
    }

    public function hasStr()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.StringConfig str = 4;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\StringConfig $var
     * @return $this
     */
    public function setStr($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\StringConfig::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Int32Config int = 5;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\Int32Config|null
     */
    public function getInt()
    {
        return $this->readOneof(5);
    }

    public function hasInt()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Int32Config int = 5;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\Int32Config $var
     * @return $this
     */
    public function setInt($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\Int32Config::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Ty = 11;</code>
     * @return int
     */
    public function getTy()
    {
        return $this->Ty;
    }

    /**
     * Generated from protobuf field <code>int32 Ty = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTy($var)
    {
        GPBUtil::checkInt32($var);
        $this->Ty = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

