<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ExecTxList</code>
 */
class ExecTxList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes stateHash = 1;</code>
     */
    protected $stateHash = '';
    /**
     * Generated from protobuf field <code>bytes parentHash = 7;</code>
     */
    protected $parentHash = '';
    /**
     * Generated from protobuf field <code>bytes mainHash = 8;</code>
     */
    protected $mainHash = '';
    /**
     * Generated from protobuf field <code>int64 mainHeight = 9;</code>
     */
    protected $mainHeight = 0;
    /**
     * Generated from protobuf field <code>int64 blockTime = 3;</code>
     */
    protected $blockTime = 0;
    /**
     * Generated from protobuf field <code>int64 height = 4;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>uint64 difficulty = 5;</code>
     */
    protected $difficulty = 0;
    /**
     * Generated from protobuf field <code>bool isMempool = 6;</code>
     */
    protected $isMempool = false;
    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 2;</code>
     */
    private $txs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stateHash
     *     @type string $parentHash
     *     @type string $mainHash
     *     @type int|string $mainHeight
     *     @type int|string $blockTime
     *     @type int|string $height
     *     @type int|string $difficulty
     *     @type bool $isMempool
     *     @type \Jason\Chain33\Kernel\Protobuf\Transaction[]|\Google\Protobuf\Internal\RepeatedField $txs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Executor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 1;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes parentHash = 7;</code>
     * @return string
     */
    public function getParentHash()
    {
        return $this->parentHash;
    }

    /**
     * Generated from protobuf field <code>bytes parentHash = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setParentHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->parentHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mainHash = 8;</code>
     * @return string
     */
    public function getMainHash()
    {
        return $this->mainHash;
    }

    /**
     * Generated from protobuf field <code>bytes mainHash = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMainHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->mainHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mainHeight = 9;</code>
     * @return int|string
     */
    public function getMainHeight()
    {
        return $this->mainHeight;
    }

    /**
     * Generated from protobuf field <code>int64 mainHeight = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMainHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->mainHeight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 blockTime = 3;</code>
     * @return int|string
     */
    public function getBlockTime()
    {
        return $this->blockTime;
    }

    /**
     * Generated from protobuf field <code>int64 blockTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->blockTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 4;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 difficulty = 5;</code>
     * @return int|string
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>uint64 difficulty = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkUint64($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isMempool = 6;</code>
     * @return bool
     */
    public function getIsMempool()
    {
        return $this->isMempool;
    }

    /**
     * Generated from protobuf field <code>bool isMempool = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMempool($var)
    {
        GPBUtil::checkBool($var);
        $this->isMempool = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxs()
    {
        return $this->txs;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 2;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\Transaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jason\Chain33\Kernel\Protobuf\Transaction::class);
        $this->txs = $arr;

        return $this;
    }

}

