<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *导出block文件头信息
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.FileHeader</code>
 */
class FileHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 startHeight = 1;</code>
     */
    protected $startHeight = 0;
    /**
     * Generated from protobuf field <code>string driver = 2;</code>
     */
    protected $driver = '';
    /**
     * Generated from protobuf field <code>string title = 3;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>bool testNet = 4;</code>
     */
    protected $testNet = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $startHeight
     *     @type string $driver
     *     @type string $title
     *     @type bool $testNet
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 startHeight = 1;</code>
     * @return int|string
     */
    public function getStartHeight()
    {
        return $this->startHeight;
    }

    /**
     * Generated from protobuf field <code>int64 startHeight = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->startHeight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string driver = 2;</code>
     * @return string
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Generated from protobuf field <code>string driver = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDriver($var)
    {
        GPBUtil::checkString($var, True);
        $this->driver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool testNet = 4;</code>
     * @return bool
     */
    public function getTestNet()
    {
        return $this->testNet;
    }

    /**
     * Generated from protobuf field <code>bool testNet = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setTestNet($var)
    {
        GPBUtil::checkBool($var);
        $this->testNet = $var;

        return $this;
    }

}

