<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.Genesis</code>
 */
class Genesis extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isrun = 1;</code>
     */
    protected $isrun = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isrun
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Executor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isrun = 1;</code>
     * @return bool
     */
    public function getIsrun()
    {
        return $this->isrun;
    }

    /**
     * Generated from protobuf field <code>bool isrun = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsrun($var)
    {
        GPBUtil::checkBool($var);
        $this->isrun = $var;

        return $this;
    }

}

