<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *区块头信息
 * 	 version : 版本信息
 *	 parentHash :父哈希
 * 	 txHash : 交易根哈希
 *	 stateHash :状态哈希
 * 	 height : 区块高度
 *	 blockTime :区块产生时的时标
 * 	 txCount : 区块上所有交易个数
 *	 difficulty :区块难度系数，
 *	 signature :交易签名
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bytes parentHash = 2;</code>
     */
    protected $parentHash = '';
    /**
     * Generated from protobuf field <code>bytes txHash = 3;</code>
     */
    protected $txHash = '';
    /**
     * Generated from protobuf field <code>bytes stateHash = 4;</code>
     */
    protected $stateHash = '';
    /**
     * Generated from protobuf field <code>int64 height = 5;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>int64 blockTime = 6;</code>
     */
    protected $blockTime = 0;
    /**
     * Generated from protobuf field <code>int64 txCount = 9;</code>
     */
    protected $txCount = 0;
    /**
     * Generated from protobuf field <code>bytes hash = 10;</code>
     */
    protected $hash = '';
    /**
     * Generated from protobuf field <code>uint32 difficulty = 11;</code>
     */
    protected $difficulty = 0;
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Signature signature = 8;</code>
     */
    protected $signature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version
     *     @type string $parentHash
     *     @type string $txHash
     *     @type string $stateHash
     *     @type int|string $height
     *     @type int|string $blockTime
     *     @type int|string $txCount
     *     @type string $hash
     *     @type int $difficulty
     *     @type \Jason\Chain33\Kernel\Protobuf\Signature $signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 version = 1;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes parentHash = 2;</code>
     * @return string
     */
    public function getParentHash()
    {
        return $this->parentHash;
    }

    /**
     * Generated from protobuf field <code>bytes parentHash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->parentHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 3;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->txHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 4;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 5;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 blockTime = 6;</code>
     * @return int|string
     */
    public function getBlockTime()
    {
        return $this->blockTime;
    }

    /**
     * Generated from protobuf field <code>int64 blockTime = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->blockTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 9;</code>
     * @return int|string
     */
    public function getTxCount()
    {
        return $this->txCount;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->txCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 10;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 difficulty = 11;</code>
     * @return int
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>uint32 difficulty = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkUint32($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Signature signature = 8;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\Signature|null
     */
    public function getSignature()
    {
        return isset($this->signature) ? $this->signature : null;
    }

    public function hasSignature()
    {
        return isset($this->signature);
    }

    public function clearSignature()
    {
        unset($this->signature);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Signature signature = 8;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\Signature $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\Signature::class);
        $this->signature = $var;

        return $this;
    }

}

