<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *记录本平行链所在区块的信息以及子根hash值
 * childHash:平行链子roothash值
 * startIndex:此平行链的第一笔交易的index索引值
 * childHashIndex:此平行链子roothash在本区块中的索引值
 * txCount:此平行链交易的个数
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.HeightPara</code>
 */
class HeightPara extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 height = 1;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>bytes hash = 3;</code>
     */
    protected $hash = '';
    /**
     * Generated from protobuf field <code>bytes childHash = 4;</code>
     */
    protected $childHash = '';
    /**
     * Generated from protobuf field <code>int32 startIndex = 5;</code>
     */
    protected $startIndex = 0;
    /**
     * Generated from protobuf field <code>uint32 childHashIndex = 6;</code>
     */
    protected $childHashIndex = 0;
    /**
     * Generated from protobuf field <code>int32 txCount = 7;</code>
     */
    protected $txCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $height
     *     @type string $title
     *     @type string $hash
     *     @type string $childHash
     *     @type int $startIndex
     *     @type int $childHashIndex
     *     @type int $txCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 height = 1;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 3;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes childHash = 4;</code>
     * @return string
     */
    public function getChildHash()
    {
        return $this->childHash;
    }

    /**
     * Generated from protobuf field <code>bytes childHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChildHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->childHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 startIndex = 5;</code>
     * @return int
     */
    public function getStartIndex()
    {
        return $this->startIndex;
    }

    /**
     * Generated from protobuf field <code>int32 startIndex = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStartIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->startIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 childHashIndex = 6;</code>
     * @return int
     */
    public function getChildHashIndex()
    {
        return $this->childHashIndex;
    }

    /**
     * Generated from protobuf field <code>uint32 childHashIndex = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setChildHashIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->childHashIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 txCount = 7;</code>
     * @return int
     */
    public function getTxCount()
    {
        return $this->txCount;
    }

    /**
     * Generated from protobuf field <code>int32 txCount = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTxCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->txCount = $var;

        return $this;
    }

}

