<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.HexTx</code>
 */
class HexTx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tx = 1;</code>
     */
    protected $tx = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tx
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tx = 1;</code>
     * @return string
     */
    public function getTx()
    {
        return $this->tx;
    }

    /**
     * Generated from protobuf field <code>string tx = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx = $var;

        return $this;
    }

}

