<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.HistoryCertStore</code>
 */
class HistoryCertStore extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes rootcerts = 1;</code>
     */
    private $rootcerts;
    /**
     * Generated from protobuf field <code>repeated bytes intermediateCerts = 2;</code>
     */
    private $intermediateCerts;
    /**
     * Generated from protobuf field <code>repeated bytes revocationList = 3;</code>
     */
    private $revocationList;
    /**
     * Generated from protobuf field <code>int64 curHeigth = 4;</code>
     */
    protected $curHeigth = 0;
    /**
     * Generated from protobuf field <code>int64 nxtHeight = 5;</code>
     */
    protected $nxtHeight = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $rootcerts
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $intermediateCerts
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $revocationList
     *     @type int|string $curHeigth
     *     @type int|string $nxtHeight
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Executor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes rootcerts = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRootcerts()
    {
        return $this->rootcerts;
    }

    /**
     * Generated from protobuf field <code>repeated bytes rootcerts = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRootcerts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->rootcerts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes intermediateCerts = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntermediateCerts()
    {
        return $this->intermediateCerts;
    }

    /**
     * Generated from protobuf field <code>repeated bytes intermediateCerts = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntermediateCerts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->intermediateCerts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes revocationList = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRevocationList()
    {
        return $this->revocationList;
    }

    /**
     * Generated from protobuf field <code>repeated bytes revocationList = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRevocationList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->revocationList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 curHeigth = 4;</code>
     * @return int|string
     */
    public function getCurHeigth()
    {
        return $this->curHeigth;
    }

    /**
     * Generated from protobuf field <code>int64 curHeigth = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurHeigth($var)
    {
        GPBUtil::checkInt64($var);
        $this->curHeigth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nxtHeight = 5;</code>
     * @return int|string
     */
    public function getNxtHeight()
    {
        return $this->nxtHeight;
    }

    /**
     * Generated from protobuf field <code>int64 nxtHeight = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNxtHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->nxtHeight = $var;

        return $this;
    }

}

