<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 支持构造多笔nobalance的交易 payAddr 可以支持 1. 地址 2. 私钥
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.NoBalanceTxs</code>
 */
class NoBalanceTxs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string txHexs = 1;</code>
     */
    private $txHexs;
    /**
     * Generated from protobuf field <code>string payAddr = 2;</code>
     */
    protected $payAddr = '';
    /**
     * Generated from protobuf field <code>string privkey = 3;</code>
     */
    protected $privkey = '';
    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     */
    protected $expire = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $txHexs
     *     @type string $payAddr
     *     @type string $privkey
     *     @type string $expire
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string txHexs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxHexs()
    {
        return $this->txHexs;
    }

    /**
     * Generated from protobuf field <code>repeated string txHexs = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxHexs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->txHexs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payAddr = 2;</code>
     * @return string
     */
    public function getPayAddr()
    {
        return $this->payAddr;
    }

    /**
     * Generated from protobuf field <code>string payAddr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->payAddr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string privkey = 3;</code>
     * @return string
     */
    public function getPrivkey()
    {
        return $this->privkey;
    }

    /**
     * Generated from protobuf field <code>string privkey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->privkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     * @return string
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExpire($var)
    {
        GPBUtil::checkString($var, True);
        $this->expire = $var;

        return $this;
    }

}

