<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *平行链区块详细信息
 * 	 blockdetail : 区块详细信息
 *	 sequence :区块序列号
 *   isSync:写数据库时是否需要刷盘
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ParaChainBlockDetail</code>
 */
class ParaChainBlockDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.BlockDetail blockdetail = 1;</code>
     */
    protected $blockdetail = null;
    /**
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     */
    protected $sequence = 0;
    /**
     * Generated from protobuf field <code>bool isSync = 3;</code>
     */
    protected $isSync = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Jason\Chain33\Kernel\Protobuf\BlockDetail $blockdetail
     *     @type int|string $sequence
     *     @type bool $isSync
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.BlockDetail blockdetail = 1;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\BlockDetail|null
     */
    public function getBlockdetail()
    {
        return isset($this->blockdetail) ? $this->blockdetail : null;
    }

    public function hasBlockdetail()
    {
        return isset($this->blockdetail);
    }

    public function clearBlockdetail()
    {
        unset($this->blockdetail);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.BlockDetail blockdetail = 1;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\BlockDetail $var
     * @return $this
     */
    public function setBlockdetail($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\BlockDetail::class);
        $this->blockdetail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     * @return int|string
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt64($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSync = 3;</code>
     * @return bool
     */
    public function getIsSync()
    {
        return $this->isSync;
    }

    /**
     * Generated from protobuf field <code>bool isSync = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSync($var)
    {
        GPBUtil::checkBool($var);
        $this->isSync = $var;

        return $this;
    }

}

