<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.PushSubscribes</code>
 */
class PushSubscribes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.PushSubscribeReq pushes = 1;</code>
     */
    private $pushes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Jason\Chain33\Kernel\Protobuf\PushSubscribeReq[]|\Google\Protobuf\Internal\RepeatedField $pushes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.PushSubscribeReq pushes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPushes()
    {
        return $this->pushes;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.PushSubscribeReq pushes = 1;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\PushSubscribeReq[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPushes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jason\Chain33\Kernel\Protobuf\PushSubscribeReq::class);
        $this->pushes = $arr;

        return $this;
    }

}

