<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *根据txhash去状态数据库中查询存储内容
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.QueryStorage</code>
 */
class QueryStorage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string txHash = 1;</code>
     */
    protected $txHash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $txHash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Storage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string txHash = 1;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>string txHash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->txHash = $var;

        return $this;
    }

}

