<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReceiptCheckTxList</code>
 */
class ReceiptCheckTxList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string errs = 1;</code>
     */
    private $errs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $errs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string errs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrs()
    {
        return $this->errs;
    }

    /**
     * Generated from protobuf field <code>repeated string errs = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->errs = $arr;

        return $this;
    }

}

