<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReportErrEvent</code>
 */
class ReportErrEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string frommodule = 1;</code>
     */
    protected $frommodule = '';
    /**
     * Generated from protobuf field <code>string tomodule = 2;</code>
     */
    protected $tomodule = '';
    /**
     * Generated from protobuf field <code>string error = 3;</code>
     */
    protected $error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $frommodule
     *     @type string $tomodule
     *     @type string $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string frommodule = 1;</code>
     * @return string
     */
    public function getFrommodule()
    {
        return $this->frommodule;
    }

    /**
     * Generated from protobuf field <code>string frommodule = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFrommodule($var)
    {
        GPBUtil::checkString($var, True);
        $this->frommodule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tomodule = 2;</code>
     * @return string
     */
    public function getTomodule()
    {
        return $this->tomodule;
    }

    /**
     * Generated from protobuf field <code>string tomodule = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTomodule($var)
    {
        GPBUtil::checkString($var, True);
        $this->tomodule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 3;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

