<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqAllExecBalance</code>
 */
class ReqAllExecBalance extends \Google\Protobuf\Internal\Message
{
    /**
     *地址列表
     *
     * Generated from protobuf field <code>string addr = 1;</code>
     */
    protected $addr = '';
    /**
     *执行器名称
     *
     * Generated from protobuf field <code>string execer = 2;</code>
     */
    protected $execer = '';
    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>
     */
    protected $stateHash = '';
    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>
     */
    protected $asset_exec = '';
    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>
     */
    protected $asset_symbol = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addr
     *          地址列表
     *     @type string $execer
     *          执行器名称
     *     @type string $stateHash
     *     @type string $asset_exec
     *     @type string $asset_symbol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     *地址列表
     *
     * Generated from protobuf field <code>string addr = 1;</code>
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     *地址列表
     *
     * Generated from protobuf field <code>string addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->addr = $var;

        return $this;
    }

    /**
     *执行器名称
     *
     * Generated from protobuf field <code>string execer = 2;</code>
     * @return string
     */
    public function getExecer()
    {
        return $this->execer;
    }

    /**
     *执行器名称
     *
     * Generated from protobuf field <code>string execer = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExecer($var)
    {
        GPBUtil::checkString($var, True);
        $this->execer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>
     * @return string
     */
    public function getAssetExec()
    {
        return $this->asset_exec;
    }

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAssetExec($var)
    {
        GPBUtil::checkString($var, True);
        $this->asset_exec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>
     * @return string
     */
    public function getAssetSymbol()
    {
        return $this->asset_symbol;
    }

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAssetSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->asset_symbol = $var;

        return $this;
    }

}

