<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *查询symbol在合约中的代币总额，如果execAddr为空，则为查询symbol在所有合约中的代币总额
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqGetExecBalance</code>
 */
class ReqGetExecBalance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string symbol = 1;</code>
     */
    protected $symbol = '';
    /**
     * Generated from protobuf field <code>bytes stateHash = 2;</code>
     */
    protected $stateHash = '';
    /**
     * Generated from protobuf field <code>bytes addr = 3;</code>
     */
    protected $addr = '';
    /**
     * Generated from protobuf field <code>bytes execAddr = 4;</code>
     */
    protected $execAddr = '';
    /**
     * Generated from protobuf field <code>string execer = 5;</code>
     */
    protected $execer = '';
    /**
     * Generated from protobuf field <code>int64 count = 6;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>bytes nextKey = 7;</code>
     */
    protected $nextKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $symbol
     *     @type string $stateHash
     *     @type string $addr
     *     @type string $execAddr
     *     @type string $execer
     *     @type int|string $count
     *     @type string $nextKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Statistic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string symbol = 1;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 2;</code>
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes addr = 3;</code>
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Generated from protobuf field <code>bytes addr = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, False);
        $this->addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes execAddr = 4;</code>
     * @return string
     */
    public function getExecAddr()
    {
        return $this->execAddr;
    }

    /**
     * Generated from protobuf field <code>bytes execAddr = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExecAddr($var)
    {
        GPBUtil::checkString($var, False);
        $this->execAddr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string execer = 5;</code>
     * @return string
     */
    public function getExecer()
    {
        return $this->execer;
    }

    /**
     * Generated from protobuf field <code>string execer = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setExecer($var)
    {
        GPBUtil::checkString($var, True);
        $this->execer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count = 6;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int64 count = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes nextKey = 7;</code>
     * @return string
     */
    public function getNextKey()
    {
        return $this->nextKey;
    }

    /**
     * Generated from protobuf field <code>bytes nextKey = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setNextKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->nextKey = $var;

        return $this;
    }

}

