<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqSignRawTx</code>
 */
class ReqSignRawTx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string addr = 1;</code>
     */
    protected $addr = '';
    /**
     * Generated from protobuf field <code>string privkey = 2;</code>
     */
    protected $privkey = '';
    /**
     * Generated from protobuf field <code>string txHex = 3;</code>
     */
    protected $txHex = '';
    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     */
    protected $expire = '';
    /**
     * Generated from protobuf field <code>int32 index = 5;</code>
     */
    protected $index = 0;
    /**
     * 签名的模式类型
     * 0：普通交易
     * 1：隐私交易
     * int32  mode  = 6;
     *
     * Generated from protobuf field <code>string token = 7;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>int64 fee = 8;</code>
     */
    protected $fee = 0;
    /**
     * bytes  newExecer = 9;
     *
     * Generated from protobuf field <code>string newToAddr = 10;</code>
     */
    protected $newToAddr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addr
     *     @type string $privkey
     *     @type string $txHex
     *     @type string $expire
     *     @type int $index
     *     @type string $token
     *           签名的模式类型
     *           0：普通交易
     *           1：隐私交易
     *           int32  mode  = 6;
     *     @type int|string $fee
     *     @type string $newToAddr
     *           bytes  newExecer = 9;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string addr = 1;</code>
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Generated from protobuf field <code>string addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string privkey = 2;</code>
     * @return string
     */
    public function getPrivkey()
    {
        return $this->privkey;
    }

    /**
     * Generated from protobuf field <code>string privkey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivkey($var)
    {
        GPBUtil::checkString($var, True);
        $this->privkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string txHex = 3;</code>
     * @return string
     */
    public function getTxHex()
    {
        return $this->txHex;
    }

    /**
     * Generated from protobuf field <code>string txHex = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHex($var)
    {
        GPBUtil::checkString($var, True);
        $this->txHex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     * @return string
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExpire($var)
    {
        GPBUtil::checkString($var, True);
        $this->expire = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 index = 5;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int32 index = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * 签名的模式类型
     * 0：普通交易
     * 1：隐私交易
     * int32  mode  = 6;
     *
     * Generated from protobuf field <code>string token = 7;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * 签名的模式类型
     * 0：普通交易
     * 1：隐私交易
     * int32  mode  = 6;
     *
     * Generated from protobuf field <code>string token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 8;</code>
     * @return int|string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->fee = $var;

        return $this;
    }

    /**
     * bytes  newExecer = 9;
     *
     * Generated from protobuf field <code>string newToAddr = 10;</code>
     * @return string
     */
    public function getNewToAddr()
    {
        return $this->newToAddr;
    }

    /**
     * bytes  newExecer = 9;
     *
     * Generated from protobuf field <code>string newToAddr = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setNewToAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->newToAddr = $var;

        return $this;
    }

}

