<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqTokenFinishCreate</code>
 */
class ReqTokenFinishCreate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string finisher_addr = 1;</code>
     */
    protected $finisher_addr = '';
    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     */
    protected $symbol = '';
    /**
     * Generated from protobuf field <code>string owner_addr = 3;</code>
     */
    protected $owner_addr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $finisher_addr
     *     @type string $symbol
     *     @type string $owner_addr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string finisher_addr = 1;</code>
     * @return string
     */
    public function getFinisherAddr()
    {
        return $this->finisher_addr;
    }

    /**
     * Generated from protobuf field <code>string finisher_addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFinisherAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->finisher_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_addr = 3;</code>
     * @return string
     */
    public function getOwnerAddr()
    {
        return $this->owner_addr;
    }

    /**
     * Generated from protobuf field <code>string owner_addr = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_addr = $var;

        return $this;
    }

}

