<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqTokenPreCreate</code>
 */
class ReqTokenPreCreate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string creator_addr = 1;</code>
     */
    protected $creator_addr = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     */
    protected $symbol = '';
    /**
     * Generated from protobuf field <code>string introduction = 4;</code>
     */
    protected $introduction = '';
    /**
     * Generated from protobuf field <code>string owner_addr = 5;</code>
     */
    protected $owner_addr = '';
    /**
     * Generated from protobuf field <code>int64 total = 6;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>int64 price = 7;</code>
     */
    protected $price = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $creator_addr
     *     @type string $name
     *     @type string $symbol
     *     @type string $introduction
     *     @type string $owner_addr
     *     @type int|string $total
     *     @type int|string $price
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string creator_addr = 1;</code>
     * @return string
     */
    public function getCreatorAddr()
    {
        return $this->creator_addr;
    }

    /**
     * Generated from protobuf field <code>string creator_addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatorAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->creator_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string introduction = 4;</code>
     * @return string
     */
    public function getIntroduction()
    {
        return $this->introduction;
    }

    /**
     * Generated from protobuf field <code>string introduction = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIntroduction($var)
    {
        GPBUtil::checkString($var, True);
        $this->introduction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_addr = 5;</code>
     * @return string
     */
    public function getOwnerAddr()
    {
        return $this->owner_addr;
    }

    /**
     * Generated from protobuf field <code>string owner_addr = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 6;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->price = $var;

        return $this;
    }

}

