<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *发送交易
 *   from : 打出地址
 *   to :接受地址
 *   amount : 转账额度
 *   note :转账备注
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqWalletSendToAddress</code>
 */
class ReqWalletSendToAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string from = 1;</code>
     */
    protected $from = '';
    /**
     * Generated from protobuf field <code>string to = 2;</code>
     */
    protected $to = '';
    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string note = 4;</code>
     */
    protected $note = '';
    /**
     * Generated from protobuf field <code>bool isToken = 5;</code>
     */
    protected $isToken = false;
    /**
     * Generated from protobuf field <code>string tokenSymbol = 6;</code>
     */
    protected $tokenSymbol = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $from
     *     @type string $to
     *     @type int|string $amount
     *     @type string $note
     *     @type bool $isToken
     *     @type string $tokenSymbol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string from = 1;</code>
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>string from = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to = 2;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>string to = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 4;</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isToken = 5;</code>
     * @return bool
     */
    public function getIsToken()
    {
        return $this->isToken;
    }

    /**
     * Generated from protobuf field <code>bool isToken = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsToken($var)
    {
        GPBUtil::checkBool($var);
        $this->isToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tokenSymbol = 6;</code>
     * @return string
     */
    public function getTokenSymbol()
    {
        return $this->tokenSymbol;
    }

    /**
     * Generated from protobuf field <code>string tokenSymbol = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->tokenSymbol = $var;

        return $this;
    }

}

