<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 环签名中的一组签名数据
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.RingSignatureItem</code>
 */
class RingSignatureItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes pubkey = 1;</code>
     */
    private $pubkey;
    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     */
    private $signature;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $pubkey
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes pubkey = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPubkey()
    {
        return $this->pubkey;
    }

    /**
     * Generated from protobuf field <code>repeated bytes pubkey = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPubkey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->pubkey = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignature($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->signature = $arr;

        return $this;
    }

}

