<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.UpgradeMeta</code>
 */
class UpgradeMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool starting = 1;</code>
     */
    protected $starting = false;
    /**
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>int64 height = 3;</code>
     */
    protected $height = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $starting
     *     @type string $version
     *     @type int|string $height
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool starting = 1;</code>
     * @return bool
     */
    public function getStarting()
    {
        return $this->starting;
    }

    /**
     * Generated from protobuf field <code>bool starting = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStarting($var)
    {
        GPBUtil::checkBool($var);
        $this->starting = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

}

