<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *钱包当前的状态
 *   isWalletLock : 钱包是否锁状态，true锁定，false解锁
 *   isAutoMining :钱包是否开启挖矿功能，true开启挖矿，false关闭挖矿
 *   isHasSeed : 钱包是否有种子，true已有，false没有
 *   isTicketLock :钱包挖矿买票锁状态，true锁定，false解锁，只能用于挖矿转账
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletStatus</code>
 */
class WalletStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isWalletLock = 1;</code>
     */
    protected $isWalletLock = false;
    /**
     * Generated from protobuf field <code>bool isAutoMining = 2;</code>
     */
    protected $isAutoMining = false;
    /**
     * Generated from protobuf field <code>bool isHasSeed = 3;</code>
     */
    protected $isHasSeed = false;
    /**
     * Generated from protobuf field <code>bool isTicketLock = 4;</code>
     */
    protected $isTicketLock = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isWalletLock
     *     @type bool $isAutoMining
     *     @type bool $isHasSeed
     *     @type bool $isTicketLock
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isWalletLock = 1;</code>
     * @return bool
     */
    public function getIsWalletLock()
    {
        return $this->isWalletLock;
    }

    /**
     * Generated from protobuf field <code>bool isWalletLock = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsWalletLock($var)
    {
        GPBUtil::checkBool($var);
        $this->isWalletLock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isAutoMining = 2;</code>
     * @return bool
     */
    public function getIsAutoMining()
    {
        return $this->isAutoMining;
    }

    /**
     * Generated from protobuf field <code>bool isAutoMining = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAutoMining($var)
    {
        GPBUtil::checkBool($var);
        $this->isAutoMining = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isHasSeed = 3;</code>
     * @return bool
     */
    public function getIsHasSeed()
    {
        return $this->isHasSeed;
    }

    /**
     * Generated from protobuf field <code>bool isHasSeed = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHasSeed($var)
    {
        GPBUtil::checkBool($var);
        $this->isHasSeed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isTicketLock = 4;</code>
     * @return bool
     */
    public function getIsTicketLock()
    {
        return $this->isTicketLock;
    }

    /**
     * Generated from protobuf field <code>bool isTicketLock = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTicketLock($var)
    {
        GPBUtil::checkBool($var);
        $this->isTicketLock = $var;

        return $this;
    }

}

