<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletTxDetails</code>
 */
class WalletTxDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.WalletTxDetail txDetails = 1;</code>
     */
    private $txDetails;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Jason\Chain33\Kernel\Protobuf\WalletTxDetail[]|\Google\Protobuf\Internal\RepeatedField $txDetails
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.WalletTxDetail txDetails = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxDetails()
    {
        return $this->txDetails;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.WalletTxDetail txDetails = 1;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\WalletTxDetail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Jason\Chain33\Kernel\Protobuf\WalletTxDetail::class);
        $this->txDetails = $arr;

        return $this;
    }

}

