<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *钱包模块存贮的tx交易详细信息
 *   tx : tx交易信息
 *   receipt :交易收据信息
 *   height :交易所在的区块高度
 *   index :交易所在区块中的索引
 *   blocktime :交易所在区块的时标
 *   amount :交易量
 *   fromaddr :交易打出地址
 *   txhash : 交易对应的哈希值
 *   actionName  :交易对应的函数调用
 *   payload: 保存额外的一些信息，主要是给插件使用
 *
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletTxDetail</code>
 */
class WalletTxDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 1;</code>
     */
    protected $tx = null;
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receipt = 2;</code>
     */
    protected $receipt = null;
    /**
     * Generated from protobuf field <code>int64 height = 3;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>int64 index = 4;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>
     */
    protected $blocktime = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>string fromaddr = 7;</code>
     */
    protected $fromaddr = '';
    /**
     * Generated from protobuf field <code>bytes txhash = 8;</code>
     */
    protected $txhash = '';
    /**
     * Generated from protobuf field <code>string actionName = 9;</code>
     */
    protected $actionName = '';
    /**
     * Generated from protobuf field <code>bytes payload = 10;</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Jason\Chain33\Kernel\Protobuf\Transaction $tx
     *     @type \Jason\Chain33\Kernel\Protobuf\ReceiptData $receipt
     *     @type int|string $height
     *     @type int|string $index
     *     @type int|string $blocktime
     *     @type int|string $amount
     *     @type string $fromaddr
     *     @type string $txhash
     *     @type string $actionName
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 1;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\Transaction|null
     */
    public function getTx()
    {
        return isset($this->tx) ? $this->tx : null;
    }

    public function hasTx()
    {
        return isset($this->tx);
    }

    public function clearTx()
    {
        unset($this->tx);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 1;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\Transaction $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\Transaction::class);
        $this->tx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receipt = 2;</code>
     * @return \Jason\Chain33\Kernel\Protobuf\ReceiptData|null
     */
    public function getReceipt()
    {
        return isset($this->receipt) ? $this->receipt : null;
    }

    public function hasReceipt()
    {
        return isset($this->receipt);
    }

    public function clearReceipt()
    {
        unset($this->receipt);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receipt = 2;</code>
     * @param \Jason\Chain33\Kernel\Protobuf\ReceiptData $var
     * @return $this
     */
    public function setReceipt($var)
    {
        GPBUtil::checkMessage($var, \Jason\Chain33\Kernel\Protobuf\ReceiptData::class);
        $this->receipt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 index = 4;</code>
     * @return int|string
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int64 index = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>
     * @return int|string
     */
    public function getBlocktime()
    {
        return $this->blocktime;
    }

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlocktime($var)
    {
        GPBUtil::checkInt64($var);
        $this->blocktime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fromaddr = 7;</code>
     * @return string
     */
    public function getFromaddr()
    {
        return $this->fromaddr;
    }

    /**
     * Generated from protobuf field <code>string fromaddr = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFromaddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->fromaddr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txhash = 8;</code>
     * @return string
     */
    public function getTxhash()
    {
        return $this->txhash;
    }

    /**
     * Generated from protobuf field <code>bytes txhash = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTxhash($var)
    {
        GPBUtil::checkString($var, False);
        $this->txhash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string actionName = 9;</code>
     * @return string
     */
    public function getActionName()
    {
        return $this->actionName;
    }

    /**
     * Generated from protobuf field <code>string actionName = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setActionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->actionName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 10;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

}

